export const CATEGORIES = [
  'Accounting',
  'Advertising Agency',
  'Architecture',
  'Art Gallery',
  'Auto Repair',
  'Bakery',
  'Bank',
  'Bar',
  'Barber Shop',
  'Beauty Salon',
  'Bicycle Shop',
  'Bookstore',
  'Cafe',
  'Car Dealer',
  'Car Rental',
  'Catering',
  'Cleaning Service',
  'Clothing Store',
  'Coffee Shop',
  'Construction',
  'Consulting',
  'Co-working Space',
  'Day Care',
  'Dentist',
  'Digital Marketing',
  'Dry Cleaning',
  'Electrician',
  'Electronics Store',
  'Event Planning',
  'Financial Advisor',
  'Fitness Center',
  'Florist',
  'Furniture Store',
  'Gas Station',
  'Graphic Design',
  'Grocery Store',
  'Gym',
  'Hair Salon',
  'Hardware Store',
  'Hospital',
  'Hotel',
  'Insurance Agency',
  'Interior Design',
  'IT Services',
  'Jewelry Store',
  'Landscaping',
  'Laundry',
  'Lawyer',
  'Library',
  'Locksmith',
  'Marketing Agency',
  'Massage Therapy',
  'Medical Clinic',
  'Moving Company',
  'Music School',
  'Nail Salon',
  'Night Club',
  'Optician',
  'Painting Service',
  'Pet Shop',
  'Pharmacy',
  'Photography',
  'Physiotherapy',
  'Plumber',
  'Printing Service',
  'Psychologist',
  'Real Estate',
  'Recruitment Agency',
  'Restaurant',
  'Roofing',
  'School',
  'Security Service',
  'Software Company',
  'Solar Energy',
  'Spa',
  'Sports Club',
  'Supermarket',
  'Tailor',
  'Tattoo Studio',
  'Taxi Service',
  'Travel Agency',
  'Tutoring',
  'Veterinary Clinic',
  'Web Design',
  'Wedding Planning',
  'Yoga Studio',
];
